
spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/legalito
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    template-loader-path: classpath:/templates/
    default-encoding: UTF-8
    suffix: .ftl
  web:
    cors:
      allowed-origins: http://localhost:4200
      allowed-methods: GET,POST,PUT,DELETE
      allowed-headers: "*"

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://legalito-db.cr28iooioav5.us-east-2.rds.amazonaws.com::5432/legalito
    username: postgres
    password: yourStrongPasswordHere
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  freemarker:
    template-loader-path: classpath:/templates/
    default-encoding: UTF-8
    suffix: .ftl
